name: Sonar Backend

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze Backend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: gym_backend/gym/gym

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Build and Analyze with Maven
        run: mvn clean verify sonar:sonar \
             -Dsonar.projectKey=Thirupathi-17_gym_backend \
             -Dsonar.organization=thirupathi-17 \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=${{ secrets.SONAR_TOKEN }}
